#ifndef SHARIZARD_WINRES_H
#define SHARIZARD_WINRES_H

#define SHIZ_WINRES_BASE 0x7a53 // little-endian 'Sz'

#define SHIZ_WINRES_IDD_TEMPLATE 0x7a53
#define SHIZ_WINRES_IDD_VACAT    0x7a54

#define SHIZ_WINRES_IDC_ALERT   0x7a53
#define SHIZ_WINRES_IDC_BANG    0x7a54
#define SHIZ_WINRES_IDC_EDITBOX 0x7a55
#define SHIZ_WINRES_IDC_CHECK   0x7a56
#define SHIZ_WINRES_IDC_TEXT    0x7a57

#define SHIZ_WINRES_IDB_HEADER 0x7a53

#endif // SHARIZARD_WINRES_H
