#ifndef CANVAS_DEPS_LAVENDER_H
#define CANVAS_DEPS_LAVENDER_H

#define CONFIG_SHIZ_CHECKBOX_MARK_CHARACTER "x"
#define CONFIG_SHIZ_RADIO_FIELD_CHARACTER   "○"
#if defined(HAVE_GFX_CHARSET)
#define CONFIG_SHIZ_RADIO_MARK_CHARACTER "•"
#else
#define CONFIG_SHIZ_RADIO_MARK_CHARACTER "x"
#endif

#endif // CANVAS_DEPS_LAVENDER_H
